[package]
name = "ctlogs"
version = "0.1.0"
authors = [ "Stephen OBrien <wayofthepie@users.noreply.github.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.36"
base64 = "0.12.3"
csv = "1.1.3"
der-parser = "4.0.1"
futures = "0.3.5"
http = "0.2.1"
reqwest = { version = "0.10.6", features = [ "json", "stream" ] }
serde = { version = "1.0.112", features = [ "derive" ] }
tokio = { version = "0.2.21", features = [ "macros", "sync", "fs", "time", "signal" ] }
x509-parser = "0.7.0"
serde_json = "1.0.56"

[dev-dependencies]
tempfile = "3.1.0"
wiremock = "0.2.2"
csv = "1.1.3"
async-dup = "1.2.1"
