[package]
name = "ctlogs"
version = "0.1.0"
authors = [ "Stephen OBrien <wayofthepie@users.noreply.github.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.2"
der-parser = "4.0.0"
reqwest = { version = "0.10.6", features = [ "json" ] }
serde = { version = "1.0.112", features = [ "derive" ] }
tokio = { version = "0.2.21", features = [ "macros" ] }
x509-parser = "0.7.0"

[dev-dependencies]
httpmock = "0.3.5"
